#!/bin/sh
#
# Copyright 2014 Google Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Just sleep for an arbitrary long time. The main process is already
# taking care of blanking.
trap '' USR2
exec sleep 86400
